// ==UserScript==
// @name           AdsBypasser
// @namespace      AdsBypasser
// @author         AdsBypasser Team
// @version        8.8.1
// @license        BSD-3-Clause
// @homepageURL    https://adsbypasser.github.io/
// @supportURL     https://github.com/adsbypasser/adsbypasser/issues
// @updateURL https://raw.githubusercontent.com/gnadgnaoh/Userscripts/release/release/adsbypasser.full.meta.js
// @downloadURL https://raw.githubusercontent.com/gnadgnaoh/Userscripts/release/release/adsbypasser.full.user.js
// @icon           https://raw.githubusercontent.com/adsbypasser/adsbypasser/v8.8.1/static/img/logo.png
// @grant          GM_deleteValue
// @grant          GM_getValue
// @grant          GM_info
// @grant          GM_openInTab
// @grant          GM_registerMenuCommand
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest
// @grant          GM.deleteValue
// @grant          GM.getValue
// @grant          GM.info
// @grant          GM.openInTab
// @grant          GM.registerMenuCommand
// @grant          GM.setValue
// @grant          GM.xmlHttpRequest
// @grant          unsafeWindow
// @noframes
// @run-at         document-start
// @connect        *
// @match          *://adsbypasser.github.io/*
// @match          *://*.14xpics.space/*
// @match          *://*.1ink.cc/*
// @match          *://*.1link.club/*
// @match          *://*.2i.cz/*
// @match          *://*.2i.sk/*
// @match          *://*.3minx.com/*
// @match          *://*.3xplanet.com/*
// @match          *://*.3xplanet.net/*
// @match          *://*.4fuk.me/*
// @match          *://*.555fap.com/*
// @match          *://*.a2zapk.io/*
// @match          *://*.adfoc.us/*
// @match          *://*.adsafelink.com/*
// @match          *://*.adshnk.com/*
// @match          *://*.adz7short.space/*
// @match          *://*.ai18.pics/*
// @match          *://*.ak.sv/*
// @match          *://*.anchoreth.com/*
// @match          *://*.anime-jav.com/*
// @match          *://*.apunkasoftware.net/*
// @match          *://*.aylink.co/*
// @match          *://*.bayimg.com/*
// @match          *://*.bcvc.ink/*
// @match          *://*.beeimg.com/*
// @match          *://*.binbox.io/*
// @match          *://*.blackwidof.org/*
// @match          *://*.blogmado.com/*
// @match          *://*.boost.ink/*
// @match          *://*.casimages.com/*
// @match          *://*.chinese-pics.com/*
// @match          *://*.clik.pw/*
// @match          *://*.clk.sh/*
// @match          *://*.cloudgallery.net/*
// @match          *://*.cn-av.com/*
// @match          *://*.cnpics.org/*
// @match          *://*.cnxx.me/*
// @match          *://*.cosplay18.pics/*
// @match          *://*.cpmlink.net/*
// @match          *://*.cpmlink.pro/*
// @match          *://*.croea.com/*
// @match          *://*.cubeupload.com/*
// @match          *://*.cutpaid.com/*
// @match          *://*.depic.me/*
// @match          *://*.directupload.eu/*
// @match          *://*.dpic.me/*
// @match          *://*.dz4link.com/*
// @match          *://*.exe-links.com/*
// @match          *://*.exeo.app/*
// @match          *://*.fappic.com/*
// @match          *://*.fastpic.org/*
// @match          *://*.fc-lc.com/*
// @match          *://*.fc-lc.xyz/*
// @match          *://*.fc2ppv.stream/*
// @match          *://*.fikfok.net/*
// @match          *://*.fir3.net/*
// @match          *://*.forex-trnd.com/*
// @match          *://*.fotosik.pl/*
// @match          *://*.get-click2.blogspot.com/*
// @match          *://*.gitlink.pro/*
// @match          *://*.gofile.download/*
// @match          *://*.goo.st/*
// @match          *://*.gplinks.co/*
// @match          *://*.hen-tay.net/*
// @match          *://*.hentai-sub.com/*
// @match          *://*.hentai4f.com/*
// @match          *://*.hentaicovid.com/*
// @match          *://*.hentaicovid.org/*
// @match          *://*.hentaipig.com/*
// @match          *://*.hentaixnx.com/*
// @match          *://*.hostpic.org/*
// @match          *://*.ibb.co/*
// @match          *://*.icutlink.com/*
// @match          *://*.idol69.net/*
// @match          *://*.im.ge/*
// @match          *://*.imagebam.com/*
// @match          *://*.imageban.ru/*
// @match          *://*.imagehaha.com/*
// @match          *://*.imagehost.at/*
// @match          *://*.imagenetz.de/*
// @match          *://*.imagenpic.com/*
// @match          *://*.imageshack.com/*
// @match          *://*.imageshimage.com/*
// @match          *://*.imagetwist.com/*
// @match          *://*.imagetwist.netlify.app/*
// @match          *://*.imageup.ru/*
// @match          *://*.imageupper.com/*
// @match          *://*.imagevenue.com/*
// @match          *://*.imagexport.com/*
// @match          *://*.imgadult.com/*
// @match          *://*.imgair.net/*
// @match          *://*.imgbase.ru/*
// @match          *://*.imgbb.com/*
// @match          *://*.imgblaze.net/*
// @match          *://*.imgbox.com/*
// @match          *://*.imgcloud.pw/*
// @match          *://*.imgdawgknuttz.com/*
// @match          *://*.imgdrive.net/*
// @match          *://*.imgfira.cc/*
// @match          *://*.imgflip.com/*
// @match          *://*.imgfrost.net/*
// @match          *://*.imghit.com/*
// @match          *://*.imgouhmde.sbs/*
// @match          *://*.imgpulse.top/*
// @match          *://*.imgtaxi.com/*
// @match          *://*.imgtraffic.com/*
// @match          *://*.imgwallet.com/*
// @match          *://*.imx.to/*
// @match          *://*.indishare.org/*
// @match          *://*.infidrive.net/*
// @match          *://*.jav-load.com/*
// @match          *://*.javball.com/*
// @match          *://*.javbee.vip/*
// @match          *://*.javlibrary.com/*
// @match          *://*.javring.com/*
// @match          *://*.javstore.net/*
// @match          *://*.javsunday.com/*
// @match          *://*.javtele.net/*
// @match          *://*.javtenshi.com/*
// @match          *://*.katfile.online/*
// @match          *://*.keeplinks.org/*
// @match          *://*.keptarolo.hu/*
// @match          *://*.kimochi.info/*
// @match          *://*.kin8-av.com/*
// @match          *://*.kin8-jav.com/*
// @match          *://*.kingofshrink.com/*
// @match          *://*.kr-av.com/*
// @match          *://*.linegee.net/*
// @match          *://*.linkpoi.me/*
// @match          *://*.linkshrink.net/*
// @match          *://*.lnk2.cc/*
// @match          *://*.loaninsurehub.com/*
// @match          *://*.lolinez.com/*
// @match          *://*.lookmyimg.com/*
// @match          *://*.mangalist.org/*
// @match          *://*.mirrored.to/*
// @match          *://*.mitly.us/*
// @match          *://*.multiup.io/*
// @match          *://*.network-loop.com/*
// @match          *://*.noelshack.com/*
// @match          *://*.oke.io/*
// @match          *://*.oko.sh/*
// @match          *://*.orangepix.is/*
// @match          *://*.otomi-games.com/*
// @match          *://*.ouo.io/*
// @match          *://*.ouo.press/*
// @match          *://*.ovabee.com/*
// @match          *://*.pahe.plus/*
// @match          *://*.payskip.org/*
// @match          *://*.pic-upload.de/*
// @match          *://*.picforall.ru/*
// @match          *://*.picstate.com/*
// @match          *://*.pig69.com/*
// @match          *://*.pilot007.org/*
// @match          *://*.pimpandhost.com/*
// @match          *://*.pixhost.to/*
// @match          *://*.pixxxar.com/*
// @match          *://*.pixxxels.cc/*
// @match          *://*.porn-pig.com/*
// @match          *://*.porn4f.com/*
// @match          *://*.porn4f.org/*
// @match          *://*.postimg.cc/*
// @match          *://*.prnt.sc/*
// @match          *://*.rintor.space/*
// @match          *://*.rlu.ru/*
// @match          *://*.ryuugames.com/*
// @match          *://*.s-porn.com/*
// @match          *://*.sfile.mobi/*
// @match          *://*.shentai-anime.com/*
// @match          *://*.short.am/*
// @match          *://*.shortmoz.link/*
// @match          *://*.shotcan.com/*
// @match          *://*.similarsites.com/*
// @match          *://*.spaste.com/*
// @match          *://*.srt.am/*
// @match          *://*.stfly.me/*
// @match          *://*.stfly.xyz/*
// @match          *://*.supercheats.com/*
// @match          *://*.sweetie-fox.com/*
// @match          *://*.swzz.xyz/*
// @match          *://*.thefileslocker.net/*
// @match          *://*.thinfi.com/*
// @match          *://*.thotpacks.xyz/*
// @match          *://*.tmearn.net/*
// @match          *://*.tnshort.net/*
// @match          *://*.trafficimage.club/*
// @match          *://*.tribuntekno.com/*
// @match          *://*.turboimagehost.com/*
// @match          *://*.turkdown.com/*
// @match          *://*.tutwuri.id/*
// @match          *://*.uncenav.com/*
// @match          *://*.uploadhaven.com/*
// @match          *://*.uploadrar.com/*
// @match          *://*.urlcash.com/*
// @match          *://*.urlgalleries.net/*
// @match          *://*.usersdrive.com/*
// @match          *://*.vipr.im/*
// @match          *://*.xcamcovid.com/*
// @match          *://*.xxpics.org/*
// @match          *://*.xxxwebdlxxx.org/*
// @match          *://*.xxxwebdlxxx.top/*
// @match          *://*.zegtrends.com/*
// ==/UserScript==
(function(){"use strict";class AdsBypasserError extends Error{constructor(t){super(t)}get name(){return"AdsBypasserError"}}function forEach(e,t){return isArrayLike(e)?Array.prototype.forEach.call(e,t):Object.keys(e).forEach(n=>t(e[n],n,e))}function every(e,t){return isArrayLike(e)?Array.prototype.every.call(e,t):Object.keys(e).every(n=>t(e[n],n,e))}function map(e,t){if(isArrayLike(e))return Array.prototype.map.call(e,t);const n=Object.assign({},e);return Object.getOwnPropertyNames(n).forEach(r=>{n[r]=t(e[r],r,e)}),n}function find(e,t){for(const[n,r]of enumerate(e)){const o=t(r,n,e);if(o!==none)return[n,r,o]}return[none,none,none]}function*enumerate(e){if(isArrayLike(e)){yield*Array.prototype.entries.call(e);return}const t=Object.getOwnPropertyNames(e);for(const n of t)yield[n,e[n]]}function isArrayLike(e){return Array.isArray(e)||isNodeList(e)}function isNodeList(e){return e.constructor.name==="NodeList"}function partial(e,...t){if(typeof e!="function")throw new AdsBypasserError("must give a function");return(...n)=>e(...t.concat(n))}function isString(e){return typeof e=="string"||e instanceof String}function nop(){}const none=nop;function wait(e){return new Promise(t=>setTimeout(t,e))}function tryEvery(e,t){return new Promise(n=>{const r=setInterval(()=>{const o=t();o!==none&&(clearInterval(r),n(o))},e)})}const patterns=[];function register(e){patterns.push(e)}function dispatchByObject(e,t){const n=map(e,(o,a)=>{if(o instanceof RegExp)return t[a].match(o);if(Array.isArray(o)){const[,,i]=find(o,l=>t[a].match(l)||none);return i!==none?i:null}throw new AdsBypasserError("invalid rule")});return every(n,o=>!!o)?n:null}function dispatchByRegExp(e,t){return t.match(e)}function dispatchByArray(e,t,n,r){const[,,o]=find(e,a=>{const i=dispatch(a,t,n,r);return i||none});return o!==none?o:null}function dispatchByString(e,t){const n=/\*|https?|file|ftp|chrome-extension/,r=/\*|(\*\.)?([^/*]+)/,o=/\/.*/,a=`^(${n.source})://(${r.source})?(${o.source})$`,i=new RegExp(a),l=e.match(i);if(!l)return null;const[,c,s,p,d,m]=l;if(c==="*"&&!/https?/.test(t.scheme)||c!==t.scheme)return null;if(c!=="file"&&s!=="*"){if(p){const u=t.host.indexOf(d);if(u<0||u+d.length!==t.host.length)return null}else if(s!==t.host)return null}return new RegExp(`^${m.replace(/[*.[\]?+#]/g,u=>u==="*"?".*":"\\"+u)}$`).test(t.path)?t:null}function dispatchByFunction(e,t,n,r){return e(t,n,r)}function dispatch(e,t,n,r){return Array.isArray(e)?dispatchByArray(e,t,n,r):typeof e=="function"?dispatchByFunction(e,t,n,r):e instanceof RegExp?dispatchByRegExp(e,t):isString(e)?dispatchByString(e,n):dispatchByObject(e,r)}function findHandler(){const e=window.location.toString(),t={scheme:window.location.protocol.slice(0,-1),host:window.location.host,path:window.location.pathname+window.location.search+window.location.hash},n={scheme:window.location.protocol,host:window.location.hostname,port:window.location.port,path:window.location.pathname,query:window.location.search,hash:window.location.hash},[r,o,a]=find(patterns,i=>{const l=dispatch(i.rule,e,t,n);return l||none});return r===none||!o.start&&!o.ready?null:{start:o.start?partial(o.start,a):nop,ready:o.ready?partial(o.ready,a):nop}}const rawUSW=getUnsafeWindow(),usw=getUnsafeWindowProxy(),GMAPI=getGreaseMonkeyAPI(),VERSION=getGMInfo().script?.version??"";function getUnsafeWindow(){let e=null;try{e=unsafeWindow}catch{try{e=(0,eval)("this").global}catch{}}return e||(0,eval)("this").window}function getGreaseMonkeyAPI(){return rawUSW.global?null:{openInTab:GM?.openInTab??GM_openInTab,getValue:GM?.getValue??promisify(GM_getValue),setValue:GM?.setValue??promisify(GM_setValue),deleteValue:GM?.deleteValue??promisify(GM_deleteValue),xmlHttpRequest:GM?.xmlHttpRequest??GM_xmlhttpRequest,registerMenuCommand:GM?.registerMenuCommand??GM_registerMenuCommand}}function promisify(e){return(...t)=>Promise.resolve(e(...t))}function getGMInfo(){return GM?.info??GM_info??{}}function needStructuredClone(){if(!(typeof mozInnerScreenX=="number"))return!1;const{scriptHandler:t}=getGMInfo();return!new Set(["Tampermonkey","Violentmonkey"]).has(t)}const MAGIC_KEY="__adsbypasser_reverse_proxy__";function getUnsafeWindowProxy(){if(!needStructuredClone())return rawUSW;const e={set(t,n,r){return n===MAGIC_KEY?!1:(t[n]=clone(r),!0)},get(t,n){if(n===MAGIC_KEY)return t;const r=t[n],o=typeof r;return r===null||o!=="function"&&o!=="object"?r:new Proxy(r,e)},apply(t,n,r){r=Array.prototype.slice.call(r),t===unsafeWindow.Object.defineProperty&&(r[0]=r[0][MAGIC_KEY]),t===unsafeWindow.Function.apply&&(n=n[MAGIC_KEY],r[1]=Array.prototype.slice.call(r[1])),t===unsafeWindow.document.querySelector&&(n=n[MAGIC_KEY]),t===unsafeWindow.document.write&&(n=n[MAGIC_KEY]);const o=clone(r);return t.apply(n,o)},construct(t,n){n=Array.prototype.slice.call(n),n.unshift(void 0);const r=clone(n),o=unsafeWindow.Function.prototype.bind;return new(o.apply(t,r))}};return new Proxy(unsafeWindow,e)}function clone(e){if(e===null||!(e instanceof Object)||e===unsafeWindow)return e;if(e instanceof String)return e.toString();if(e instanceof Function)return exportFunction(e,unsafeWindow,{allowCrossOriginArguments:!0});if(e instanceof Array){const n=new unsafeWindow.Array;for(let r=0;r<e.length;r++)n.push(clone(e[r]));return n}const t=new unsafeWindow.Object;return forEach(e,(n,r)=>{t[r]=clone(n)}),t}const MANIFEST=[{key:"version",default_:0,verify:e=>typeof e=="number"&&e>=0,normalize:parseInt},{key:"align_center",default_:!0,verify:e=>typeof e=="boolean",normalize:Boolean,label:"Align Center",help:"Align image to the center if possible.",type:"checkbox"},{key:"change_background",default_:!0,verify:e=>typeof e=="boolean",normalize:Boolean,label:"Change Background",help:"Use Firefox-like image background.",type:"checkbox"},{key:"redirect_image",default_:!0,verify:e=>typeof e=="boolean",normalize:Boolean,label:"Redirect Image",help:"Directly open image link if possible.",type:"checkbox"},{key:"scale_image",default_:!0,verify:e=>typeof e=="boolean",normalize:Boolean,label:"Scale Image",help:"Scale image to fit window.",type:"checkbox"},{key:"log_level",default_:1,verify:e=>typeof e=="number"&&e>=0&&e<=2,normalize:parseInt,label:"Log Level",help:"0: quiet, 1: default, 2: verbose",type:"select",menu:[[0,"0 (quiet)"],[1,"1 (default)"],[2,"2 (verbose)"]]}];async function sanityCheck(){const e=await Promise.all(MANIFEST.map(n=>GMAPI.getValue(n.key))),t={};MANIFEST.forEach((n,r)=>{let o=e[r];n.verify(o)||(o=n.default_),t[n.key]=o}),await Promise.all(Object.entries(t).map(([n,r])=>GMAPI.setValue(n,r)))}function waitForPage(){return new Promise(e=>{if(document.readyState==="complete"&&usw.render)return e();const t=()=>{document.readyState==="complete"&&usw.render&&(clearInterval(n),e())},n=setInterval(t,50);document.addEventListener("DOMContentLoaded",t)})}async function dumpConfig(){const e=await Promise.all(MANIFEST.map(n=>GMAPI.getValue(n.key))),t={};return MANIFEST.forEach((n,r)=>t[n.key]=e[r]),t}async function loadConfig(){await sanityCheck(),register({rule:{host:/^adsbypasser\.github\.io$/,path:/^\/configure\.html$/},async ready(){await waitForPage(),usw.commit=async n=>{for(const[r,o]of Object.entries(n))await GMAPI.setValue(r,o)};const e=await dumpConfig(),t=MANIFEST.reduce((n,r)=>(!r.type||r.key==="version"||(n[r.key]={type:r.type,value:e[r.key],label:r.label,help:r.help},r.type==="select"&&(n[r.key].menu=r.menu)),n),{});usw.render({version:e.version,options:t})}})}function log(e,t){t=Array.prototype.slice.call(t),isString(t[0])?t[0]="AdsBypasser: "+t[0]:t.unshift("AdsBypasser:");const n=console[e];typeof n=="function"&&n.apply(console,t)}function debug(){log("debug",arguments)}function info(){log("info",arguments)}function warn(){log("warn",arguments)}class AjaxError extends AdsBypasserError{constructor(t,n,r,o,a,i){super(`${t} ${n} got ${a}`),this._method=t,this._url=n,this._data=r,this._headers=o,this._status=a,this._response=i}get name(){return"AjaxError"}get method(){return this._method}get url(){return this._url}get data(){return this._data}get headers(){return this._headers}get status(){return this._status}get response(){return this._response}}function*flattenObject(e){if(e)for(const[t,n]of Object.entries(e))if(Array.isArray(n))for(const r of n)yield[[t,""],r];else if(typeof n=="object")for(const[r,o]of flattenObject(n))yield[[t,...r],o];else yield[[t],n]}function flattenKey(e){const[t,...n]=e;return`${t}${n.map(r=>`[${r}]`)}`}function deepJoin(e,t){const n=Object.getOwnPropertyNames(t);return map(n,o=>{const a=t[o],i=`${e}[${o}]`;return typeof a=="object"?deepJoin(i,a):[i,a].map(encodeURIComponent).join("=")}).join("&")}function toQuery(e){const t=typeof e;if(e===null||t!=="string"&&t!=="object")return"";if(t==="string")return e;if(e instanceof String)return e.toString();const n=Object.getOwnPropertyNames(e);return map(n,r=>{const o=e[r];return typeof o=="object"?deepJoin(r,o):[r,o].map(encodeURIComponent).join("=")}).join("&")}function toForm(e){const t=typeof e;if(e===null||t!=="string"&&t!=="object")return"";if(t==="string")return e;if(e instanceof String)return e.toString();const n=new FormData;for(const[r,o]of flattenObject(e))n.append(flattenKey(r),o);return n}function ajax(e,t,n,r){debug("ajax",e,t,n,r);const o=document.createElement("a");o.href=t;const i={Host:o.hostname||window.location.host,Origin:window.location.origin,Referer:window.location.href,"X-Requested-With":"XMLHttpRequest"};return forEach(i,(l,c)=>{r[c]===none?delete r[c]:r[c]=l}),n&&(r["Content-Type"]?.indexOf("json")>=0?n=JSON.stringify(n):r["Content-Type"]?.indexOf("multipart")>=0?n=toForm(n):n=toQuery(n),r["Content-Length"]=n.length),new Promise((l,c)=>{GMAPI.xmlHttpRequest({method:e,url:t,data:n,headers:r,onload(s){s=typeof s.responseText<"u"?s:this,s.status!==200?c(new AjaxError(e,t,n,r,s.status,s.responseText)):l(s.responseText)},onerror(s){s=typeof s.responseText<"u"?s:this,c(new AjaxError(e,t,n,r,s.status,s.responseText))}})})}function get$1(e,t,n){return t=toQuery(t),t=t?`?${t}`:"",n=n||{},ajax("GET",e+t,"",n)}function post$1(e,t,n){const r={"Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"};return n&&forEach(n,(o,a)=>{r[a]=o}),ajax("POST",e,t,r)}function setCookie(e,t){document.cookie=`${e}=${t};path=${location.pathname};`}function getCookie(e){const[,t]=find(document.cookie.split(";"),r=>{if(r.replace(/^\s*([a-zA-Z0-9-_]+)=.+$/,"$1")!==e)return none});return t===none?null:t.replace(/^\s*[a-zA-Z0-9-_]+=([^;]+).?$/,"$1")||null}function resetCookies(){const e=location.hostname,t=e.replace(/^www\./,""),n=e.replace(/^(\w+\.)+?(\w+\.\w+)$/,"$2"),r=new Date(1e3).toUTCString();forEach(document.cookie.split(";"),o=>{const a=o.replace(/^\s*(\w+)=.+$/,"$1");document.cookie=`${a}=;expires=${r};`,document.cookie=`${a}=;path=/;expires=${r};`;const i=(l,c,s)=>`${l}=;path=/;domain=${c};expires=${s};`;document.cookie=i(a,e,r),document.cookie=i(a,t,r),document.cookie=i(a,n,r)})}class DomNotFoundError extends AdsBypasserError{constructor(t){super(`\`${t}\` not found`)}get name(){return"DomNotFoundError"}}function querySelector(e,t){(!t||!t.querySelector)&&(t=document);const n=t.querySelector(e);if(!n)throw new DomNotFoundError(e);return n}function querySelectorOrNull(e,t){try{return querySelector(e,t)}catch{return null}}function querySelectorAll(e,t){return(!t||!t.querySelectorAll)&&(t=document),t.querySelectorAll(e)}function toDOM(e){try{return new DOMParser().parseFromString(e,"text/html")}catch{throw new AdsBypasserError("could not parse HTML to DOM")}}function remove(e,t){const n=querySelectorAll(e,t);forEach(n,r=>{debug("removed",r),r.remove()})}function block(e,t=document){let n;if(isString(e))n=()=>remove(e,t);else if(typeof e=="function")n=o=>{o.addedNodes.forEach(a=>{e(a)&&a.parentNode.removeChild(a)})};else throw new TypeError("wrong selector");new MutationObserver(o=>{o.forEach(a=>n(a))}).observe(t,{childList:!0,subtree:!0})}function searchFromScriptsByRegExp(e,t){const n=querySelectorAll("script",t),[,,r]=find(n,o=>o.textContent.match(e)||none);return r===none?null:r}function searchFromScriptsByString(e,t){const n=querySelectorAll("script",t),[,r]=find(n,o=>{const a=o.textContent.indexOf(e);return a<0?none:a});return r===none?null:r.textContent}function searchFromScripts(e,t){return e instanceof RegExp?searchFromScriptsByRegExp(e,t):isString(e)?searchFromScriptsByString(e,t):null}function prepare(e){return document.body||(document.body=document.createElement("body")),document.body.appendChild(e),wait(0)}async function get(e){const t=document.createElement("a");t.href=e;let n=!1;t.addEventListener("click",o=>{o.stopPropagation(),n=!0},!0),await prepare(t),t.click();const r=setInterval(()=>{if(n){info("already clicked"),clearInterval(r);return}info("try again"),t.click()},500)}async function post(e,t={}){const n=document.createElement("form");n.method="post",n.action=e,forEach(t,(r,o)=>{const a=document.createElement("input");a.type="hidden",a.name=o,a.value=r,n.appendChild(a)}),await prepare(n),n.submit()}async function openLink(e,t={}){if(!isString(e)||!e){warn("false URL");return}const n=typeof t.referer>"u"?!0:t.referer,r=t.post,o=window.location.toString();if(info(`${o} -> ${e}`),r){await post(e,r);return}if(n){await get(e);return}window.top.location.replace(e)}function removeAllTimer(){let e=window.setInterval(nop,10);for(;e>0;)window.clearInterval(e--);for(e=window.setTimeout(nop,10);e>0;)window.clearTimeout(e--)}function nuke(e){try{usw.document.write("nuked by AdsBypasser, leading to ...<br/>")}catch(n){warn("nuke failed",n)}const t=document.createElement("a");t.href=e,t.textContent=e,document.body.appendChild(t)}function generateRandomIP(){return[0,0,0,0].map(()=>Math.floor(Math.random()*256)).join(".")}function evil(script){return((GM,GM_deleteValue,GM_getValue,GM_openInTab,GM_registerMenuCommand,GM_setValue,GM_xmlhttpRequest,unsafeWindow,window)=>eval(script))()}const RESOURCE_ROOT=`https://raw.githubusercontent.com/adsbypasser/adsbypasser/v${VERSION}/static`,ALIGN_CENTER=`${RESOURCE_ROOT}/css/align_center.css`,SCALE_IMAGE=`${RESOURCE_ROOT}/css/scale_image.css`,BACKGROUND_IMAGE=`${RESOURCE_ROOT}/img/imagedoc-darknoise.png`;async function openImage(e,t={}){const n=!!t.replace,r=!!t.referer;if(n){await replaceBody(e);return}await GMAPI.getValue("redirect_image")&&await openLink(e,{referer:r})}function enableScrolling(){const e=document.compatMode==="CSS1Compat"?document.documentElement:document.body;e.style.overflow=""}function toggleShrinking(){this.classList.toggle("adsbypasser-shrinked")}function checkScaling(){const e=this.naturalWidth,t=this.naturalHeight,n=document.documentElement.clientWidth,r=document.documentElement.clientHeight;(e>n||t>r)&&!this.classList.contains("adsbypasser-resizable")?(this.classList.add("adsbypasser-resizable","adsbypasser-shrinked"),this.addEventListener("click",toggleShrinking)):e<=n&&t<=r&&this.classList.contains("adsbypasser-resizable")&&(this.removeEventListener("click",toggleShrinking),this.classList.remove("adsbypasser-shrinked","adsbypasser-resizable"))}function scaleImage(e){appendStyleURL(SCALE_IMAGE),e.naturalWidth&&e.naturalHeight?checkScaling.call(e):e.addEventListener("load",checkScaling);let t=0;window.addEventListener("resize",()=>{clearTimeout(t),t=setTimeout(checkScaling.bind(e),100)})}function changeBackground(){document.body.style.backgroundColor="#222222",document.body.style.backgroundImage=`url('${BACKGROUND_IMAGE}')`}function alignCenter(){appendStyleURL(ALIGN_CENTER)}function injectStyle(e,t){remove("style, link[rel=stylesheet]"),e.id="adsbypasser-wrapper",t.id="adsbypasser-image"}function appendStyleURL(e){const t=document.createElement("link");t.rel="stylesheet",t.type="text/css",t.href=e,document.head.appendChild(t)}async function replaceBody(e){if(!await GMAPI.getValue("redirect_image")||!e){e||warn("false url");return}info(`replacing body with \`${e}\` ...`),removeAllTimer(),enableScrolling(),document.body=document.createElement("body");const n=document.createElement("div");document.body.appendChild(n);const r=document.createElement("img");r.src=e,n.appendChild(r);const o=await GMAPI.getValue("align_center"),a=await GMAPI.getValue("scale_image");(o||a)&&injectStyle(n,r),o&&alignCenter(),await GMAPI.getValue("change_background")&&changeBackground(),a&&scaleImage(r)}const _={AdsBypasserError,evil,find,forEach,generateRandomIP,info,none,partial,register,tryEvery,wait,warn};function $(e,t){return querySelector(e,t)}$.$=querySelectorOrNull,$.$$=querySelectorAll,$.block=block,$.get=get$1,$.getCookie=getCookie,$.nuke=nuke,$.openImage=openImage,$.openLink=openLink,$.post=post$1,$.remove=remove,$.removeAllTimer=removeAllTimer,$.resetCookies=resetCookies,$.searchFromScripts=searchFromScripts,$.setCookie=setCookie,$.toDOM=toDOM,$.window=usw,_.register({rule:{host:/^ak\.sv$/},async ready(){await _.wait(1e3),$("html").click(),await _.wait(6e3);const t=$('a[class="download_button"]');await $.openLink(t)}}),_.register({rule:{host:/^(www\.)?apunkasoftware\.net$/},async ready(){const e=$("div#proceed-now > a#dlink");await $.openLink(e.href)}}),_.register({rule:{host:/^thefileslocker\.net$/},async ready(){$("#downloadbtn").click()}}),_.register({rule:{host:[/^(www\.)?indishare\.org$/,/^uploadrar\.com$/]},async ready(){const e=$("button#downloadbtn.downloadbtn");e.removeAttribute("disabled"),e.click()}}),_.register({rule:{host:/^infidrive\.net$/},async ready(){await _.wait(4e4),$("button.inline-flex:nth-child(2)").click()}}),_.register({rule:{host:/^katfile\.online$/},async ready(){const e=$('a[id="dlink"]');await $.openLink(e.href)}}),_.register({rule:{host:/^(www\.)?keeplinks\.org$/},async ready(){$('[id="btnproceedsubmit"]').click()}}),_.register({rule:{host:/^(www\.)?mirrored\.to$/,path:/^\/files\//},async ready(){$(".secondary").click()}}),_.register({rule:{host:/^multiup\.io$/},async ready(){$("#download-button").click()}}),_.register({rule:{host:/^sfile\.mobi$/},async ready(){await _.wait(8e3),$("#download").click()}}),_.register({rule:{host:/^uploadhaven\.com$/,path:/^\/download\//},async ready(){await _.wait(18e3),$("#submitFree").click()}}),_.register({rule:{host:/^usersdrive\.com$/},async ready(){const e=$(".btn-download");await $.openLink(e.href)}}),_.register({rule:{host:/^1ink\.cc$/},async ready(){const e=$("#countingbtn");await $.openLink(e.href)}}),_.register({rule:{host:/^1link\.club$/},async ready(){const e=$("#download.btn");await $.openLink(e.href)}}),_.register({rule:{host:/^a2zapk\.io$/},async ready(){const e=$("#dlbtn li a");await $.openLink(e.href)}}),_.register({rule:{host:/^adfoc\.us$/},async ready(){const e=$(".skip");await $.openLink(e.href)}}),_.register({rule:{host:/^adshnk\.com$/},async ready(){await _.wait(16e3),$('button[class="ui right labeled icon button primary huge fluid"]').click(),await _.wait(18e3);const t=$('a[id="final_redirect"]');await $.openLink(t.href)}}),_.register({rule:{host:/^www\.adz7short\.space$/},async ready(){const e=$("#continue");await _.wait(1e4),e.click()}}),_.register({rule:{host:/^anchoreth\.com$/,query:/v=([^&]+)/},async start(e){await $.openLink(atob(e.query[1]))}}),_.register({rule:{host:/^bcvc\.ink$/},async ready(){await _.wait(5e3),$("#getLink").click()}}),_.register({rule:[{host:/^(www\.)?([a-zA-Z0-9]+\.)?binbox\.io$/,path:/\/o\/([a-zA-Z0-9]+)/}],async start(e){const t=window.atob(e.path[1]);await $.openLink(t)}}),_.register({rule:{host:/^blogmado\.com/},async ready(){await _.wait(3e3),$(".btn").click()}}),_.register({rule:{host:/^boost\.ink$/},async start(){const e=$("body").getAttribute("result");if(e)await $.openLink(atob(e));else return}}),_.register({rule:{host:/^cpmlink\.net$/},async ready(){const e=$("#btn-main");await $.openLink(e.href)}}),_.register({rule:{host:/^cutpaid\.com$/},async ready(){const e=$(".btn-lg.get-link");await _.wait(9e3),await $.openLink(e.href)}}),_.register({rule:{host:/^forex-trnd\.com$/},async ready(){await _.wait(1e4),$(".get-link").click()}}),_.register({rule:{host:[/^exe-links\.com$/,/^exeo\.app$/]},async ready(){$(".link-button.button").click(),await _.wait(2e3),$(".link-button").click(),await _.wait(6e3),$(".link-button.get-link").click()}}),_.register({rule:{host:/^fc-lc\.(com|xyz)$/},async ready(){await _.wait(2e3),$(".btn-primary.btn-captcha.mb-4").click()}}),_.register({rule:{host:/^loaninsurehub\.com$/},async ready(){const e=$("#glink");e&&e.click(),await _.wait(12e3),$.remove("#overlay");const t=$("#surl");t&&t.click()}}),_.register({rule:{host:/^fir3\.net$/},async ready(){await _.wait(12e3),$(".btn.btn-success.btn-lg.get-link").click()}}),_.register({rule:{host:/^get-click2\.blogspot\.com$/},async ready(){const e=$("button#gotolink");e.removeAttribute("disabled"),await _.wait(1),e.click()}}),_.register({rule:{host:/^gplinks\.co$/},async ready(){await _.wait(8e3),$(".get-link").click()}}),_.register({rule:{host:/^hen-tay\.net$/,path:/^\/go\//},async ready(){const e=$("#download_url div a");await $.openLink(e.href)}}),_.register({rule:{host:/^icutlink\.com$/},async ready(){await _.wait(1e4);const e=$(".btn-success.btn-lg.get-link");await $.openLink(e)}}),_.register({rule:{host:/^zegtrends\.com$/},async ready(){await _.wait(12e3),$("div > button.bsub").click()}}),_.register({rule:{host:/^imagetwist\.netlify\.app$/},async ready(){const e=$("center h2 p a, .btn-dark");await $.openLink(e.href)}}),_.register({rule:{host:/^www\.javlibrary\.com$/,query:/url=([^&]+)/},async start(e){await $.openLink(decodeURIComponent(e.query[1]))}}),_.register({rule:{host:/^kimochi\.info$/,path:/^\/inter$/},async ready(){const e=$("a#next");await $.openLink(e.href)}}),_.register({rule:{host:/^(www\.)?kingofshrink\.com$/},async ready(){const e=$("#textresult > a");await $.openLink(e.href)}}),_.register({rule:{host:/^linegee\.net$/},async ready(){await _.wait(3e3),$(".btn-xs").click()}}),_.register({rule:{host:/^link\.turkdown\.com$/},async ready(){await _.wait(5e3);const e=$(".btn-success.btn-lg.get-link");await $.openLink(e.href)}}),(function(){_.register({rule:{host:[/^adsafelink\.com$/,/^dz4link\.com$/,/^tmearn\.net$/,/^payskip\.org$/,/^clik\.pw$/,/^aylink\.co$/,/^(clk|oko)\.sh$/,/^cpmlink\.pro$/,/^gitlink\.pro$/,/^mitly\.us$/,/^oke\.io$/,/^pahe\.plus$/,/^thotpacks\.xyz$/]},async ready(){await new t().call()}});class e{constructor(){this._overlaySelector=['[class$="Overlay"]',"#__random_class_name__","#headlineatas","#myModal",".opacity_wrapper","#overlay"].join(", "),this._formSelector=["#go-link",".go-link","#originalLink.get-link",'form[action="/links/go"]'].join(", ")}removeOverlay(){$.remove(this._overlaySelector),$.block(this._overlaySelector,document.body),setInterval(()=>{document.body.style.overflow="initial"},500)}removeFrame(){$.remove("iframe")}async call(){if(!await this.prepare())return;const i=await this.getMiddleware();if(!i){this.withoutMiddleware();return}const l=await this.getURL(i);await $.openLink(l)}}class t extends e{async prepare(){if(this.removeOverlay(),!$.$("#captchaShortlink, div.g-recaptcha"))return!0;if(_.info("recaptcha detected, stop"),_.info("trying to listen submit button"),!$.$("#invisibleCaptchaShortlink"))return!1}async submitListen(a){new MutationObserver(()=>{a.disabled||a.click()}).observe(a,{attributes:!0})}async getMiddleware(){return await n(this._formSelector)}withoutMiddleware(){$("#link-view").submit()}async getURL(a){for(;;){await _.wait(1e3);try{const i=await r(a);if(i)return i}catch(i){_.warn(i)}}}}async function n(o){let a=$.window.$;for(;!a;)await _.wait(50),a=$.window.$;const i=a(o);return i.length>0?i:null}function r(o){return new Promise((a,i)=>{o.is("a")&&o.attr("href")&&a(o.attr("href")),$.window.$.ajax({dataType:"json",type:"POST",url:o.attr("action"),data:o.serialize(),success:c=>{c.url?a(c.url):i(new _.AdsBypasserError(c.message))},error:(c,s,p)=>{_.warn(c,s,p),i(new _.AdsBypasserError("request error"))}})})}})(),_.register({rule:{host:/^linkpoi\.me$/},async ready(){await _.wait(6e3),$(".btn.btn-primary.btn-block.redirect.get-link").click()}}),_.register({rule:{host:/^linkshrink\.net$/,path:/^\/[a-zA-Z0-9]+$/},async start(){$.window._impspcabe=0},async ready(){let e=$.searchFromScripts(/revC\("([^"]+)"\)/);e=atob(e[1]),await $.openLink("/"+e)}}),_.register({rule:{host:/^lnk2\.cc$/,path:/^\/go\//},async ready(){$.remove("iframe, .popupOverlay"),await _.wait(18e3),$("#getLink").click()}}),_.register({rule:{host:/^www\.lolinez\.com$/,query:/\?(.+)/},async start(e){await $.openLink(e.query[1])}}),_.register({rule:{host:/^mangalist\.org$/},async ready(){await _.wait(1e3),$(".btn-primary.url.text-center").click()}}),_.register({rule:{host:/^network-loop\.com$/,query:/u=([^&]+)/},async start(){await _.wait(3e3);const n=document.querySelector("#print_button").shadowRoot.querySelector("a#pb_2");await $.openLink(n.href)}}),_.register({rule:{host:/^otomi-games\.com$/,path:/^\/go\//},async ready(){const e=$("#wpsafe-link a");await $.openLink(e.href)}}),_.register({rule:{host:/^(www\.)?ouo\.(io|press)$/,path:/(^\/\w+$|^\/go\/\w+$)/},async ready(){$("form").submit()}}),_.register({rule:{host:/^preview\.rlu\.ru$/},async ready(){const e=$("#content > .long_url > a");await $.openLink(e.href)}}),_.register({rule:{host:/^www\.ryuugames\.com$/,query:/^\?eroge=/},async ready(){const e=$("#wpsafe-link a");await $.openLink(e.href)}}),_.register({rule:{host:/^(short|srt)\.am$/},async ready(){await _.wait(6e3),$(".skipp").click()}}),_.register({rule:{host:[/^goo\.st$/,/^shortmoz\.link$/,/^swzz\.xyz$/]},async ready(){$(".btn-primary").click()}}),_.register({rule:{host:/^(www\.)?similarsites\.com$/,path:/^\/goto\/([^?]+)/},async start(e){let t=e.path[1];/^https?:\/\//.test(t)||(t="http://"+t),await $.openLink(t)}}),_.register({rule:{host:/^www\.spaste\.com$/,path:/^\/site\//},async ready(){await _.wait(15e3),$("#template-contactform-submit").click()}}),_.register({rule:{host:/^stfly\.(me|xyz)$/},async ready(){$(".btn-captcha.m-2.form-send").click()}}),_.register({rule:{host:/^(www\.)?supercheats\.com$/,path:/^\/interstitial\.html$/,query:/(?:\?|&)oldurl=([^&]+)(?:$|&)/},async start(e){await $.openLink(e.query[1])}}),_.register({rule:{host:/^thinfi\.com$/},async ready(){const e=$("div p a");await $.openLink(e.href)}}),_.register({rule:{host:/^go\.tnshort\.net$/},async ready(){await _.wait(3e3);const e=$('a[class="btn btn-success btn-lg get-link"]');await $.openLink(e.href)}}),_.register({rule:{host:/^tribuntekno\.com$/},async ready(){const e=$.$("#lite-human-verif-button");e&&e.click();const t=$.$("#lite-start-sora-button");t&&t.click()}}),_.register({rule:{host:/^tutwuri\.id$/},async ready(){await _.wait(1e3),$("#btn-1").click(),await _.wait(12e3),$("#btn-2").click(),$("#btn-3").click()}}),_.register({rule:{host:/(^|\.)urlcash\.com$/},async ready(){if($.window&&$.window.linkDestUrl){await $.openLink($.window.linkDestUrl);return}const e=document.body.innerHTML.match(/linkDestUrl = '(.+)'/);if(e){await $.openLink(e[1]);return}}}),_.register({rule:{host:/^urlgalleries\.net$/},async ready(){await _.wait(1e3),$("#overlay.butstyle").click()}}),_.register({rule:{host:/^bayimg\.com$/},async ready(){const e=$("#mainImage");await $.openImage(e.src)}}),_.register({rule:{host:/^beeimg\.com$/},async ready(){const e=$("#beeimage");await $.openImage(e.src)}}),_.register({rule:{host:/^www\.casimages\.com$/},async ready(){const e=$("div.logo a img");await $.openImage(e.src)}}),_.register({rule:{host:[/^14xpics\.space$/,/^www\.2i\.(cz|sk)$/,/^imgcloud\.pw$/,/^www\.imghit\.com$/,/^img\.javstore\.net$/,/^imgpulse\.top$/,/^lookmyimg\.com$/,/^orangepix\.is$/,/^pilot007\.org$/,/^rintor\.space$/,/^shotcan\.com$/,/^(img\.)?trafficimage\.club$/],path:/^\/(image|i)\/.*/},async ready(){const e=$('link[rel="image_src"]');await $.openImage(e.href)}}),_.register({rule:{host:/^cubeupload\.com$/},async ready(){const e=$("img.galleryBigImg");await $.openImage(e.src)}}),_.register({rule:{host:/^(depic|dpic)\.me$/},async ready(){const e=$("#pic");await $.openImage(e.src)}}),_.register({rule:{host:[/^www\.directupload\.eu$/,/^www\.noelshack\.com$/]},async ready(){const e=$('meta[property="og:image"]');await $.openImage(e.content)}}),_.register({rule:{host:/^fastpic\.org$/,path:/^\/view\//},async ready(){const e=$.$("#imglink");if(e){await $.openLink(e.href);return}const t=$.searchFromScripts(/loading_img = '([^"]+)';/);await $.openLink(t[1])}}),_.register({rule:{host:/^www\.fotosik\.pl$/},async ready(){const e=$(".simple-photo img");await $.openImage(e.src)}}),_.register({rule:{host:/^www\.hostpic\.org$/},async ready(){const e=$("#photo");await $.openImage(e.src)}}),_.register({rule:{host:/^www\.imagebam\.com$/},async ready(){let e=$.$("#continue > a");e&&e.click(),e=$(".main-image"),await $.openImage(e.src)}}),_.register({rule:{host:/^imageban\.ru$/},async ready(){const e=$("#img_main");await $.openImage(e.src)}}),_.register({rule:[{host:[/^www\.imagehost\.at$/,"pixxxar.com"],path:/^\/image\//},{host:/^im\.ge$/,path:/^\/i\//}],async ready(){const e=$('meta[property="og:image"]');await $.openImage(e.content)}}),_.register({rule:{host:/^www\.imagenetz\.de$/},async ready(){const e=$(".img-rounded.img-responsive");await $.openImage(e.src)}}),_.register({rule:{host:/^imageshack\.com$/,path:/^\/i\//},async ready(){const e=$("#lp-image");await $.openImage(e.src)}}),_.register({rule:{host:[/^croea\.com$/,/^fappic\.com$/,/^imagehaha\.com$/,/^imagenpic\.com$/,/^imageshimage\.com$/,/^imagetwist\.com$/,/^imagexport\.com$/,/^vipr\.im$/]},async ready(){const e=$("img.pic");await $.openImage(e.src)}}),_.register({rule:{host:[/^imageup\.ru$/,/^imageupper\.com$/,/^imgbox\.com$/]},async ready(){const e=$("#img, #image");await $.openImage(e.src)}}),_.register({rule:{host:/^www\.imagevenue\.com$/},async ready(){const e=$.$("#main-image");if(e){await $.openImage(e.src);return}const t=$('a[title="Continue to ImageVenue"]');await $.openLink(t.href)}}),_.register({rule:{host:[/^cloudgallery\.net$/,/^imgair\.net$/,/^imgblaze\.net$/,/^imgfira\.cc$/,/^imgfrost\.net$/,/^img[a-z]{2,10}\.(sbs|shop)$/,/^pic[a-z]{2,10}\.(sbs|shop)$/,/^pix[a-z]{2,10}\.sbs$/]},async ready(){const e=$.searchFromScripts(/imgbg\.src = "([^"]+)";/);await $.openImage(e[1],{referer:!0})}}),_.register({rule:{host:[/^(imgbase|picforall)\.ru$/]},async ready(){let e=$("#pay_thumb_img img, #d1 table tbody tr td img");e=e.getAttribute("onclick"),e=e.match(/mshow\('(.+)'\)/),e=e[1],await $.openImage(e)}}),_.register({rule:{host:[/^ibb\.co$/,/^imgbb\.com$/]},async ready(){const e=$(".image-viewer-container img");await $.openImage(e.src)}}),_.register({rule:{host:[/^(www\.)?(imgadult|imgtaxi|imgwallet)\.com$/,/^(www\.)?imgdrive\.net$/]},async ready(){let e=$('meta[property="og:image"]');e=e.content.replace("small","big"),await $.openImage(e)}}),_.register({rule:{host:/^imgflip\.com$/},async ready(){const e=$("#im");await $.openImage(e.src)}}),_.register({rule:{host:/^imgtraffic\.com$/,path:/^\/a-1\/(.+)\.jpeg\.html/},async start(){const e=window.location.href.replace("/a-","/").replace(".html","");await $.openImage(e)}}),_.register({rule:{host:/^imgtraffic\.com$/,path:/^\/i-1\/(.+)\.jpeg\.html/},async start(){const e=window.location.href.replace("/i-","/").replace(".html","");await $.openImage(e)}}),_.register({rule:{host:/^imgtraffic\.com$/,path:/^\/n-1\/(.+)\.jpeg\.html/},async start(){const e=window.location.href.replace("/n-","/").replace(".html","");await $.openImage(e)}}),_.register({rule:{host:/^imgtraffic\.com$/,path:/^\/z-1\/(.+)\.jpeg\.html/},async start(){const e=window.location.href.replace("/z-","/").replace(".html","");await $.openImage(e)}}),_.register({rule:{host:/^imx\.to$/},async ready(){let e=$.$("#continuebutton, .button");e&&e.click(),e=$(".centred"),await $.openImage(e.src)}}),_.register({rule:["https://3minx.com/upload/en/*","https://4fuk.me/upload/en/*","https://555fap.com/upload/en/*","https://ai18.pics/upload/en/*","https://anime-jav.com/upload/en/*","https://blackwidof.org/upload/en/*","https://chinese-pics.com/upload/en/*","https://cn-av.com/upload/en/*","https://cnpics.org/upload/en/*","https://cnxx.me/upload/en/*","https://cosplay18.pics/upload/en/*","https://fc2ppv.stream/upload/en/*","https://fikfok.net/upload/en/*","https://gofile.download/upload/en/*","https://hentai-sub.com/upload/en/*","https://hentai4f.com/upload/en/*","https://hentaicovid.com/uploads/en/*","https://hentaicovid.org/upload/en/*","https://hentaipig.com/upload/en/*","https://hentaixnx.com/upload/en/*","https://idol69.net/upload/en/*","https://javball.com/upload/en/*","https://javbee.vip/upload/en/*","https://javring.com/upload/en/*","https://javsunday.com/upload/en/*","https://javtele.net/upload/en/*","https://kin8-av.com/upload/en/*","https://kin8-jav.com/upload/en/*","https://kr-av.com/upload/en/*","https://ovabee.com/upload/en/*","https://pig69.com/upload/en/*","https://porn-pig.com/upload/en/*","https://porn4f.com/upload/en/*","https://porn4f.org/upload/en/*","https://s-porn.com/upload/en/*","https://shentai-anime.com/upload/en/*","https://sweetie-fox.com/upload/en/*","https://xcamcovid.com/upload/en/*","https://xxpics.org/upload/en/*"],async ready(){const e=$('meta[property="og:image"]');await $.openImage(e.content)}}),_.register({rule:{host:/^image\.javbee\.vip$/,path:/^\/en\//},async ready(){const e=$('meta[property="og:image"]');await $.openLink(e.content)}}),_.register({rule:{host:/^image\.javbee\.vip$/,path:/^\/ib\//},async ready(){const e=$("a");await $.openImage(e.href)}}),_.register({rule:{host:/^keptarolo\.hu$/,path:/^(\/[^/]+\/[^/]+)$/},async start(e){await $.openImage("http://www.keptarolo.hu/kep"+e.path[1])}}),_.register({rule:{host:/^www\.pic-upload\.de$/},async ready(){const e=$(".preview_picture_2b");await $.openImage(e.src)}}),_.register({rule:{host:/^picstate\.com$/,path:/^\/view\/full\/.*/},async ready(){const e=$("#image_container a img");await $.openImage(e.src)}}),_.register({rule:{host:/^(www\.)?pimpandhost\.com$/,path:/^\/image\/\d+/,query:/^\?size=original/},async ready(){const e=$("#overflow-wrapper img.original");await $.openImage(e.src)}}),_.register({rule:{host:/^(www\.)?pimpandhost\.com$/,path:/^\/image\/\d+/},async start(e){await $.openImage(e.path+"?size=original")}}),_.register({rule:[{host:/^(www\.)?pixhost\.to$/,path:/^\/show\//},{host:[/^3xplanet\.(com|net)$/,/^jav-load\.com$/,/^javtenshi\.com$/,/^uncenav\.com$/],path:/^\/viewimage\//}],async ready(){$.remove("iframe, #ad");let e=$.$("#all");e&&(e.style.display=""),e=$("#show_image, #image"),await $.openImage(e.src)}}),_.register({rule:{host:[/^pixxxels\.cc$/,/^postimg\.cc$/]},async ready(){const t=$("#download").href.replace("?dl=1","");await $.openImage(t,{referer:!0})}}),_.register({rule:{host:/^prnt\.sc$/,path:/\.html$/}}),_.register({rule:{host:/^prnt\.sc$/},async ready(){const e=$("#screenshot-image");await $.openImage(e.src)}}),_.register({rule:{host:/^www\.turboimagehost\.com$/,path:/^\/p\//},async ready(){const e=$("#imageid");await $.openImage(e.src)}}),_.register({rule:{host:[/^imgdawgknuttz\.com$/,/^xxxwebdlxxx\.(org|top)$/]},async ready(){const e=$(".centred, .centred_resized");await $.openImage(e.src)}});const isSafari=Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor")>0;function disableWindowOpen(){try{usw.open=()=>({closed:!1})}catch{warn("cannot mock window.open")}usw.alert=nop,usw.confirm=nop}function disableLeavePrompt(e){if(!e)return;const t={set:()=>info("blocked onbeforeunload")};e.onbeforeunload=void 0,isSafari?e.__defineSetter__("onbeforeunload",t.set):usw.Object.defineProperty(e,"onbeforeunload",{configurable:!0,enumerable:!1,get:void 0,set:t.set});const n=e.addEventListener;e.addEventListener=function(r){if(r==="beforeunload"){info("blocked addEventListener onbeforeunload");return}return n.apply(this,arguments)}}function changeTitle(){document.title+=" - AdsBypasser"}function waitDOM(){return new Promise(e=>{if(document.readyState!=="loading"){e();return}document.addEventListener("DOMContentLoaded",()=>e())})}async function beforeDOMReady(e){const t=await dumpConfig();info(`working on
%s 
with
%s`,window.location.toString(),JSON.stringify(t)),disableLeavePrompt(usw),disableWindowOpen(),await e.start()}async function afterDOMReady(e){disableLeavePrompt(usw.document.body),changeTitle(),await e.ready()}async function main(){if(rawUSW.top!==rawUSW.self)return;GMAPI.registerMenuCommand("AdsBypasser - Configure",()=>{GMAPI.openInTab("https://adsbypasser.github.io/configure.html")}),await loadConfig();const e=findHandler();e&&(await beforeDOMReady(e),await waitDOM(),await afterDOMReady(e))}main().catch(e=>warn(e))})();
